import { DICTIONARY } from "@/constants/dictionary";
import { BugOff } from "lucide-react";
import { ICON_POOL } from "./components/public/IconPool";


/**
 * Parses a Gemini-generated HTML string into a structured array of sections.
 * Each section has an optional H2 title and a body HTML string.
 *
 * @param html - Raw HTML content from Gemini
 * @returns Array of { title, body } section objects
 */
export const parseHtmlIntoSections = (html: string): { title: string | null; body: string }[] => {
  // 1. Remove any stray <h1> tags generated by AI, as the H1 is rendered separately by the page.
  const cleanHtml = html.replace(/<h1\b[^>]*>[\s\S]*?<\/h1>/gi, "");

  // 2. Split the HTML at any <h2... tag. This handles attributes like <h2 class="...">
  const parts = cleanHtml.split(/(?=<h2\b[^>]*>)/i);
  const sections: { title: string | null; body: string }[] = [];

  let introText = "";

  for (const part of parts) {
    if (!part.trim()) continue;

    // Use [\s\S]* to match across newlines, and account for potential attributes in <h2>
    const match = part.match(/^<h2\b[^>]*>([\s\S]*?)<\/h2>/i);
    if (match) {
      // Extract the inner text of H2 and strip any nested tags (e.g., <strong>)
      const title = match[1].replace(/<[^>]+>/g, "").trim();
      const body = part.replace(/^<h2\b[^>]*>[\s\S]*?<\/h2>/i, "").trim();

      if (introText) {
        // If there is accumulated intro text, prepend it to the first H2's body
        sections.push({ title, body: introText + "<br/><br/>" + body });
        introText = ""; // Reset so it isn't appended to others
      } else {
        sections.push({ title, body });
      }
    } else {
      // If it doesn't start with H2, it's intro text
      introText += part.trim() + " ";
    }
  }

  // Rare fallback: If the AI generated absolutely no H2s at all
  if (introText && sections.length === 0) {
    sections.push({ title: DICTIONARY.global.overview, body: introText });
  }

  return sections;
}

export type Section = {
  title: string | null;
  body: string;
};

/**
 * Calculates the best icons for a given array of sections based on tags.
 */
export const getSectionIcons = (sections: Section[]) => {
  const usedIndices = new Set<number>();

  return sections.map((section, idx) => {
    // Rule: The last section (About the company) is always the OWNER logo
    if (idx === sections.length - 1) return DICTIONARY.admin.ownerShortcut;

    const text = ((section.title || "") + " " + section.body).toLowerCase();

    // Smart match: Find the first unused icon that matches the text
    let bestIndex = -1;
    for (let i = 0; i < ICON_POOL.length; i++) {
      if (usedIndices.has(i)) continue;

      if (ICON_POOL[i].tags.some((tag: string) => text.includes(tag))) {
        bestIndex = i;
        break;
      }
    }

    // If no keyword matches (or all matched ones are used), pick the next unused icon
    if (bestIndex === -1) {
      for (let i = 0; i < ICON_POOL.length; i++) {
        if (!usedIndices.has(i)) {
          bestIndex = i;
          break;
        }
      }
    }

    // Fallback: If all 11 icons in the pool are exhausted
    if (bestIndex === -1) {
      return BugOff;
    }

    usedIndices.add(bestIndex);
    return ICON_POOL[bestIndex].icon;
  });
};
