export const IMAGE_UPLOAD_ERRORS = {
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  FILE_REQUIRED: "FILE_REQUIRED",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  CONFIGURATION_FAILED: "CONFIGURATION_FAILED",
  UPLOAD_FAILED: "UPLOAD_FAILED",
} as const;

export type ImageUploadErrorCode = keyof typeof IMAGE_UPLOAD_ERRORS;
